server:
  port: 80
  tomcat:
      uri-encoding: utf-8

logging:
    file: mylog.log
    level:
        gr.blog.mapper: debug

spring:
    mvc:
        favicon:
            enable: false
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/blog?allowMultiQueries=true
        username: root
        #password: root
        #aliyun Mysql 密码
        password: XXXXXXX
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  #Mapper.xml所在的位置
  mapper-locations: classpath:mapping/*.xml
  #entity扫描的包名
  type-aliases-package: gr.blog.model
  #开启MyBatis的二级缓存
  configuration:
      cache-enabled: true

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# Enable template caching.
thymeleaf:
    cache: false
# Check that the templates location exists.
    check-template-location: true
# Content-Type value.
    content-type: text/html
# Enable MVC Thymeleaf view resolution.
    enabled: true
# Template encoding.
    encoding: UTF-8
# Comma-separated list of view names that should be excluded from resolution.
    excluded-view-names:
# Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    mode: HTML
# Prefix that gets prepended to view names when building a URL.
    prefix: classpath:/templates/
# Suffix that gets appended to view names when building a URL.
    suffix: .html
    template-resolver-order:
# Order of the template resolver in the chain. spring.thymeleaf.view-names= # Comma-separated list of view names that can be resolved.